OGtest/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)), # Admin config
    url(r'^$', 'shop.views.home', name='home'), # Home config
    # customer register
    url(r'^customers/register/$', 'shop.views.register_user'),
    url(r'^customers/register_success/$', 'shop.views.register_success'),     
    # customer login/logout
    url(r'^customers/login/$', 'shop.views.login'),
    url(r'^customers/auth/$', 'shop.views.auth_view'),
    url(r'^customers/logout/$', 'shop.views.logout'),
    url(r'^customers/login_success/$', 'shop.views.login_success'),
    url(r'^customers/login_invalid/$', 'shop.views.login_invalid'),
    # customer account
    url(r'^customers/account/$', 'shop.views.account_detail'),
    # store page
    url(r'^stores/books/$', 'shop.views.bookstore'),
    url(r'^stores/movies/$', 'shop.views.moviestore'),
    url(r'^stores/drinks/$', 'shop.views.drinkstore'),
    # session-based shopping cart
    url(r'^addToCart/$', 'shop.views.addToCart'),
    url(r'^view_cart/$', 'shop.views.view_cart'),
    # checkout
    url(r'^checkout/$', 'shop.views.checkout'),
    url(r'^order_process/$', 'shop.views.order_process'),
    url(r'^order_invalid/$', 'shop.views.order_invalid'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
import os
from OGtest.settings import MEDIA_URL
from django.db import models
from time import time 
from django.contrib.auth.models import User

# Create your models here.

def update_filename(instance, filename):
  path = 'product'
  format = str(instance.id) + ".jpg"
  return os.path.join(path, format)

class Store(models.Model):
  name = models.CharField(max_length=100)

  def __unicode__(self):
    return self.name

class Manufacturer(models.Model):
  name = models.CharField(max_length=100)
  category = models.CharField(max_length=100, default='MISC')

  def __unicode__(self):
    return self.name

class Product(models.Model):
  store = models.ForeignKey(Store)
  name = models.CharField(max_length=200)
  manufacturer = models.ForeignKey(Manufacturer)
  dollar_price = models.DecimalField(max_digits=6, 
                                     decimal_places=2)
  description = models.TextField()
  photo = models.ImageField(upload_to=update_filename,
                            blank=True)

  def __unicode__(self):
    return self.name  

class Order(models.Model):
  user = models.ForeignKey(User)
  products = models.ManyToManyField(Product, through="Orderdetail")
  date = models.DateTimeField()  

  def __unicode__(self):
    return "o" + str(self.id)

  def get_total_price(self):
    od_list = Orderdetail.objects.filter(order = self)
    total_price = 0
    for od in od_list:
      total_price += od.quantity * od.product.dollar_price
    return '$' + str(total_price)

  def get_recipient(self):
    shipping = shipping_info.objects.filter(order = self)
    if shipping:
      sp = shipping[0]   
      return sp.recipient
    else:
      return "recipient not found!"

  def get_shipping_address(self):
    shipping = shipping_info.objects.filter(order = self)
    if shipping:
      sp = shipping[0]
      street = sp.street
      city = sp.city
      state = sp.state
      return street + ", " + city + ", " + state
    else:
      return "shipping address not found!"


class Orderdetail(models.Model):
  order = models.ForeignKey(Order)
  product = models.ForeignKey(Product)
  quantity = models.PositiveIntegerField()

  def __unicode__(self):
    return "od" + str(self.id)

class shipping_info(models.Model):
  order = models.ForeignKey(Order)
  recipient = models.CharField(max_length=100)
  street = models.CharField(max_length=500)
  city = models.CharField(max_length=100)
  state = models.CharField(max_length=100)
  postal_code = models.IntegerField(max_length=10)

class payment_info(models.Model):
  order = models.ForeignKey(Order)
  card_holder = models.CharField(max_length=100)
  card_num = models.IntegerField(max_length=20)
  expire_date = models.DateField()

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustRegForm(UserCreationForm):
  email = forms.EmailField(required=True)
  first_name = forms.CharField(required=True)
  last_name = forms.CharField(required=True)

  class Meta:
    model = User
    fields = ('username', 'email', 'first_name', 'last_name', 
              'password1', 'password2')

  def save(self, commit=True):
    user = super(CustRegForm, self).save(commit=False)
    user.email = self.cleaned_data['email']
    user.first_name = self.cleaned_data['first_name']
    user.last_name = self.cleaned_data['last_name']   

    if commit:
      user.save()

    return user

shop/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django.core.context_processors import csrf
from forms import CustRegForm
from django.template import RequestContext
from shop.models import Product, Order, Orderdetail, shipping_info, payment_info
import datetime

import OGtest.settings
# Create your views here.

def home(request):
  return render_to_response('shop/index.html', context_instance=RequestContext(request))

def register_user(request):
  if request.method == 'POST':
    form = CustRegForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect('/customers/register_success')
    else:
      return HttpResponseRedirect('/customers/register_invalid')
  
  reg_args={}
  reg_args.update(csrf(request))

  return render_to_response('shop/register.html', reg_args)

def register_success(request):
  return render_to_response('shop/register_success.html', context_instance=RequestContext(request))

def login(request):
  login_args = {}
  login_args.update(csrf(request))
  if "next" in request.GET:
    login_args.update({"next": request.GET["next"]})

  return render_to_response('shop/login.html', login_args)

def auth_view(request):
  username = request.POST.get('username', '')
  password = request.POST.get('password', '')
  user = auth.authenticate(username=username, password=password)

  if user is not None:
    auth.login(request, user)
    if "next" in request.GET:
      return redirect(request.GET["next"])
    else:
      return redirect('/customers/login_success')
  else:
    return redirect('/customers/login_invalid')

def login_success(request):
  return render_to_response('shop/login_success.html', context_instance=RequestContext(request))

def login_invalid(request):
  login_args = {}
  login_args.update(csrf(request))

  return render_to_response('shop/login_invalid.html', login_args)

def logout(request):
  auth.logout(request)
  return render_to_response('shop/logout.html')

def account_detail(request):
  user = request.user
  order_list = Order.objects.filter(user=user)
  return render_to_response('shop/account.html', {'orders': order_list}, context_instance=RequestContext(request))

def bookstore(request):
  return render_to_response('shop/bookstore.html', {'products': Product.objects.filter(store__name='Books'), 'repath': request.path}, context_instance=RequestContext(request))

def moviestore(request):
  return render_to_response('shop/moviestore.html', {'products': Product.objects.filter(store__name='Movies'), 'repath': request.path}, context_instance=RequestContext(request))

def drinkstore(request):
  return render_to_response('shop/drinkstore.html', {'products': Product.objects.filter(store__name='Drinks'), 'repath': request.path}, context_instance=RequestContext(request))

def addToCart(request, quantity=1):
  # ajax request to update the session
  cart = request.session.get('cart', {})
  product_id = request.GET['product_id']
  if product_id in cart:
    if int(cart[product_id]) != 0:
      cart[product_id] = int(cart[product_id]) + quantity
  else:
    cart[product_id] = quantity
  request.session['cart'] = cart
  return HttpResponse("add ok")

# helper function  
def update_cart(request):
  # called by the 'update' button on the cart page
  cart = request.session.get('cart', {})
  newcart = {}
  for product_id in cart:
    cart[product_id] = request.POST.get(product_id) 
    # delete product which quantity == 0 in the update cart
    if int(cart[product_id]) != 0:
      newcart[product_id] = cart[product_id]
  request.session['cart'] = newcart

def view_cart(request):
  if request.method == 'POST':
    ### UPDATE CART INFO FIRST if directed from the update submit form    
    update_cart(request)

  cartsummary = get_cart_summary(request)
  if "checkout" in request.POST:
    return redirect("/checkout")
  else:
    return render_to_response('shop/cart.html', {'carts': cartsummary}, context_instance=RequestContext(request))

@login_required(login_url ='/customers/login/')  # Ask user to login before they checkout
def checkout(request):
  cartsummary = get_cart_summary(request)
  return render_to_response('shop/checkout.html', {'carts': cartsummary}, context_instance=RequestContext(request))

# helper function
def get_cart_summary(request):
  cart = request.session.get('cart', {})
  cartsummary = []
  for product_id in cart:
    p = Product.objects.get(id=product_id)
    el = {}
    el.update({"product": p,
               "quantity": cart[product_id],
               "total_price": float(p.dollar_price) * int(cart[product_id])
              })
    cartsummary.append(el)
  return cartsummary

def order_process(request):
  if request.method == 'POST':
    ### UPDATE CART INFO FIRST
    update_cart(request)
    newcart = request.session.get('cart', {})

    if len(newcart) == 0:
      return redirect("/order_invalid")
    else:
      # create an order object first
      user = request.user
      curdate = datetime.datetime.now()
      order = Order(user = user, date = curdate)
      order.save()

      # create a list of order detail objects with PK = order, product
      for product_id in newcart:
        p = Product.objects.get(id=product_id)
        quantity = newcart[product_id]
        orderdetail = Orderdetail(order = order, product = p, quantity = quantity)
        orderdetail.save()

      if shipValidate(request):
        # then a shipping_info object with FK order
        recipient = request.POST['recipient']
        street = request.POST['street']
        city = request.POST['city']
        state = request.POST['state']
        postal_code = request.POST['postalcode']
        shippinginfo = shipping_info(order = order, 
                                  recipient = recipient, 
                                  street = street, 
                                  city = city, 
                                  state = state, 
                                  postal_code = postal_code)
        shippinginfo.save()
      else:
        return redirect("/order_invalid")

      if paymentValidate(request):
        # then a payment_info object with FK order
        card_holder = request.POST['cardholder']
        card_num = request.POST['cardnum']
        expire_date = request.POST['expiredate']
        paymentinfo = payment_info(order = order, 
                                card_holder = card_holder, 
                                card_num = card_num, 
                                expire_date = expire_date)
        paymentinfo.save()
      else:
        return redirect("/order_invalid")

      # clean the cart info stored in the session    
      request.session['cart'] = {}
      return render_to_response('shop/order_success.html', context_instance=RequestContext(request))

def order_invalid(request):
  return render_to_response('shop/order_invalid.html', context_instance=RequestContext(request))

def shipValidate(request):
  ship_list = ["recipient", "street", "city", "state", "postalcode"]
  for k in ship_list:
    if k in request.POST:
      if not request.POST[k]:
        return False
  return True

def paymentValidate(request):
  ship_list = ["cardholder", "cardnum", "expiredate"]
  for k in ship_list:
    if k in request.POST:
      if not request.POST[k]:
        return False
  return True

templates/shop/account.html
{% extends 'shop/base.html' %}

{% block containercontent %}
  
  {% if orders %}
  <div class="container table-responsive">
  <h2>Hi, {{user.username}}!</h2>
  <table class='table-bordered'>
    <tr>
      <th>Order Info</th>
      <th>Contained Items</th>
    </tr>
  {% for order in orders %}
    <tr>
      <td>
        <ul class="list-group">
          <li class="list-group-item">Created on: {{order.date}}</li>
          <li class="list-group-item">Recipient: {{order.get_recipient}}</li>
          <li class="list-group-item">Shipping to: {{order.get_shipping_address}}</li>
          <li class="list-group-item">Total amount: {{order.get_total_price}}</li>
        </ul>
      </td>
      <td>
        <ul class="list-group">
          {% for detail in order.orderdetail_set.all %}
            <li class="list-group-item">
              <div class="row">
                <div class="col-md-1" style="padding: 0 15px 0 5px">
                  <img class="media-object pull-left" src="{{detail.product.photo.url}}" alt="..." style="width: 36px; height: 40px">
                </div>
                <div class ="col-md-11">
                  {{detail.product.name}}<br>quantity: {{detail.quantity}} 
                </div>
              </div>
            </li>
          {% endfor %}
        </ul>
      </td>
    </tr>
  {% endfor %}
  </table>
  </div>
  {% endif %}

{% endblock %}

templates/shop/bookstore.html
{% extends 'shop/store.html' %}

templates/shop/checkout.html
{% extends 'shop/base.html' %}

{% block containercontent %}
    <form id="myForm" action="/order_process/" method='POST'>{% csrf_token %}
    <h3>Order Summary</h3>
    <table class="table">
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
        {% for detail in carts %}
        <tr>
            <td>{{ detail.product.name }}</td>
            <td><input type="number" min='0' step='1' name='{{ detail.product.id }}' value='{{ detail.quantity }}'></td>
            <td class="pricetd">{{ detail.total_price }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td>Total Summary: </td>
            <td id='mySum'></td>
        </tr>
    </table>
    
    <h3>Shipping Information</h3>
    <div class='form-group form-inline'>
      <label for='recipient'>Shipping information</label>
      <input type='text' class="form-control" name='recipient' maxlength='30' placeholder='Enter recipient name'/>
    </div>
    <div class='form-group form-inline'>
      <label for='street'>Address</label>
      <input type='text' class="form-control" name='street' maxlength='100' placeholder='Enter street address'/>
      <input type='text' class="form-control" name='city' maxlength='100' placeholder='Enter city name'/>
      <input type='text' class="form-control" name='state' maxlength='100' placeholder='Enter state name'/>
      <input type='text' class="form-control" name='postalcode' maxlength='100' placeholder='Enter postal code'/>
    </div>

    <h3>Payment Information</h3>
    <div class='form-group form-inline'>
      <label for='cardholder'>Cardholder name</label>
      <input type='text' class="form-control" name='cardholder' maxlength='30' placeholder='Enter cardholder name'/>
    </div>
    <div class='form-group form-inline'>
      <label for='cardnum'>Card information</label>
      <input type='text' class="form-control" name='cardnum' maxlength='100' placeholder='Enter card number'/>
      <label for='expire_month'>Expiration Date: </label>
      <input type='date' class="form-control" name='expiredate'/>
    </div>

    <button type="submit" class="btn btn-default">Submit</button>    
    </form>
{% endblock %}

{% block bodyscriptadd %}
  <script>
  $(document).ready(function(){
     colSum();
  });

  function colSum() {
    var sum=0;
    //iterate through each input and add to sum
    $('.pricetd').each(function() {
            sum += parseFloat($(this).text());
    });
    //change value of total
    $('#mySum').html(sum.toFixed(2));
  }

  </script>
{% endblock %}

templates/shop/drinkstore.html
{% extends 'shop/store.html' %}

templates/shop/index.html
{% extends "shop/base.html" %}

{% block additionalnavbar %}

{% endblock %}

{% block containercontent %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>Hello, welcome to Qingyuan's Secret Shop!</h1>
    <p>Click the store links on the navbar to visit different stores, and then go checkout by clicking your cart on the left.</p>
  </div>
{% endblock %}

templates/shop/login.html
{% extends 'shop/base.html' %}

{% block containercontent %}

  <div class='container' style="padding: 70px 0 0 0">
  {% if next %}
  <form action='/customers/auth/?next={{next}}' method='POST' class="form-signin" role="form">
  {% else %}
  <form action='/customers/auth/' method='POST' class="form-signin" role="form">
  {% endif %}
    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign in</h2>
    <input type="text" name='username' class="form-control" placeholder="Username" required autofocus>
    <input type="password" name='password' class="form-control" placeholder="Password" required>
    <label class="checkbox">
      <input type="checkbox" value="remember-me"> Remember me
    </label>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </form>
  </div>

{% endblock %}

templates/shop/login_invalid.html
{% extends 'shop/base.html' %}

{% block containercontent %}

  <div class='container' style="padding: 70px 0 0 0">
  <form action='/customers/auth/' method='POST' class="form-signin" role="form">
    {% csrf_token %}
    <h2 class="form-signin-heading">The username or password is wrong, Please sign in again</h2>
    <input type="text" name='username' class="form-control" placeholder="Email address" required autofocus>
    <input type="password" name='password' class="form-control" placeholder="Password" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </form>
  </div>

{% endblock %}

templates/shop/login_success.html
{% extends 'shop/base.html' %}

{% block containercontent %}

  <div class='container' style='padding: 70px 0 0 0'>
    {% if user.is_authenticated %}
      <h2> Welcome, {{user.username}} </h2>
      <h2> Click <a href='/'>here</a> to return to the homepage</h2>
    {% endif %}
  </div>
{% endblock %}

templates/shop/logout.html
{% extends 'shop/base.html' %}

{% block containercontent %}

  <div class='container' style='padding: 70px 0 0 0'>
      <h2> You've been successfully logged out! </h2>
      <h2> Click <a href='/'>here</a> to return to the homepage</h2>
  </div>
{% endblock %}

templates/shop/moviestore.html
{% extends 'shop/store.html' %}

templates/shop/order_invalid.html
{% extends 'shop/base.html' %}

{% block containercontent %}
  <h2>Your order is invalid! Please review your cart and checkout again!</h2>
{% endblock %}

templates/shop/order_success.html
{% extends 'shop/base.html' %}

{% block containercontent %}
 <h2>success!</h2>
{% endblock %}

templates/shop/register_success.html
{% extends 'shop/base.html' %}

{% block containercontent %}

  <div class='container' style='padding: 70px 0 0 0'>
    <h2>you have successfully registered! Click <a href='/customers/login'>here</a> to login!</h2>
  </div>
{% endblock %}

templates/shop/store.html
{% extends 'shop/base.html' %}

{% block containercontent %}
  <div class='contaier' style='padding: 70px 0 0 0'>
  <div class="row">
    {% if products %}
    {% for product in products %}
    <div class="col-lg-4">
      <img src="{{product.photo.url}}" style="width: 180px; height: 200px" />
      <p><h2>{{product.name}}</h2><i class="fa fa-usd"></i> {{product.dollar_price}}</p>
      <p class="comment">{{product.description}}</p>
      <p>
        <button class="btn btn-primary" onclick="return addToCart({{product.id}});">Add to cart</a>
      </p>
    </div><!-- /.col-lg-4 -->
    {% endfor %}
    {% endif %}
  </div><!-- /.row -->
  </div>
{% endblock %}

{% block bodyscriptadd %}
<script type="text/javascript" src="http://viralpatel.net/blogs/demo/jquery/jquery.shorten.1.0.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".comment").shorten({
           "showChars" : 200,
        });
    });

function addToCart(product_id) {
  var myData = {};
  myData['product_id'] = product_id;

  $.ajax({
    url:'/addToCart/',
    data: myData,
    success: function() {
      alert("Added to cart successfully!");
    },
    error: function(xhr,errmsg,err) { alert(xhr.status + "wrong: " + xhr.responseText);
    }
  })
};
</script>
{% endblock %}